// SPDX-License-Identifier: GPL-2.0-or-later
/* autogenerated by configure / config.status */

/* IF YOU ARE INCLUDING THIS FILE FROM A DAEMON OR ZEBRA, YOU ARE PROBABLY
 * DOING SOMETHING WRONG.  Check for / add a library function that retrieves
 * the path you need.
 *
 * Only libfrr and watchfrr should be including this file.
 */

/* the replacements for these are emitted by AX_SUBST_EXPANDED, which also
 * adds the e_ prefix
 */
#define FRR_RUNSTATE_PATH	"/usr/local/var/run/frr"
#define FRR_LIBSTATE_PATH	"/usr/local/var/lib/frr"
#define YANG_MODELS_PATH	"/usr/local/share/yang"
#define MODULE_PATH		"/usr/local/lib/frr/modules"
#define SCRIPT_PATH		"/usr/local/etc/frr/scripts"

/* for extra footgunning, this one has a trailing slash */
#define SYSCONFDIR		"/usr/local/etc/frr/"

#define VTYSH_BIN_PATH		"/usr/local/bin/vtysh"
#define WATCHFRR_SH_PATH	"/usr/local/sbin/watchfrr.sh"
